[font]
size = 8.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15

[env]
TERM = "xterm-256color"

[shell]
program = "/usr/bin/zsh"
args = ["-l", "-c", "tmux ls | grep -v attached && tmux attach || tmux"]
