[font]
size = 10

[font.glyph_offset]
x = 0
y = 0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0

[window]
opacity = 0.95

[env]
TERM = "xterm-256color"

[shell]
program = "/usr/bin/zsh"
