[[manager.prepend_keymap]]
on   = "<C-s>"
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on   = "<C-y>"
run  = 'plugin --sync clip_copy'
desc = "Copies the file path to the windows clipboard."
