version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = "os"
foreground = "p:gold"
background = "p:black"
template = "{{ if .WSL }}WSL at {{ end }}{{.Icon}} "
style = "diamond"
trailing_diamond = "\ue0b4 "
leading_diamond = "\ue0b6"

[blocks.segments.properties]
macos = "mac"


[[blocks.segments]]
type = "path"
style = "plain"
foreground = "p:gold"
background = "p:black"
template = "{{ .Path }}"

[blocks.segments.properties]
style = "agnoster_short"
folder_separator_icon	= " 󰅂 "
max_depth = 3
[[blocks.segments]]
type = "git"
plain = "plain"
foreground = "p:gold_dark"
background = "transparent"
template = " {{.HEAD }}{{ if or (.Working.Changed) (.Staging.Changed)}}*{{end}}<cyan>{{ if gt .Behind 0 }} 󰶡 {{end}}{{ if gt .Ahead 0 }} 󰶣 {{end}}</>"

[blocks.segments.properties]
fetch_status = true


[[blocks]]
type = "prompt"
alignment = "right"
overflow = "hide"

[[blocks.segments]]
type = "session"
style = "plain"
foreground = "p:gold"
background = "p:black"
template = "{{ if .SSHSession }} {{ end }}{{ .UserName }}</>@<cyan>{{ .HostName }} "

[[blocks]]
type = "prompt"
alignment = "right"
overflow = "hide"

[[blocks.segments]]
background = "#306998"
foreground = "#FFE873"
leading_diamond = "\ue0b6"
style = "diamond"
template = "\ue235 {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}"
trailing_diamond = "\ue0b4 "
type = "python"

[[blocks.segments]]
type = "project"
style = "diamond"
leading_diamond = "\ue0b6"
trailing_diamond = "\ue0b4 "
foreground = "#193549"
background = "#ffeb3b"
template = " {{ if .Error }}{{ .Error }}{{ else }}{{ if .Version }} {{.Version}}{{ end }} {{ if .Name }}{{ .Name }}{{ end }}{{ end }} "

[[blocks]]
type = "rprompt"
overflow = 'hide'
newline = true


[[blocks.segments]]
type = 'executiontime'
style = 'plain'
foreground = 'yellow'
background = 'transparent'


[blocks.segments.properties]
threshold = 5000
style = 'round'

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

[[blocks.segments]]
type = "text"
style = "plain"
foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}magenta{{end}}",

]
foreground = "magenta"
background = "transparent"
template = " "

[transient_prompt]
foreground = "magenta"
background = "transparent"
template = " "
foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}magenta{{end}}",

]

[secondary_prompt]
foreground = 'magenta'
background = 'transparent'
template = ' '

[palette]
gold = '#d4af37'
gold_dark = '#a39370'
black = '#251f11'
